/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

class AppTest {
    private ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;

    @BeforeEach
    public void setUpStreams() {
        this.outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(this.outContent));
    }

    @AfterEach
    public void restoreStreams() {
        System.setOut(originalOut);
    }

    @Test
    void testPrintBonusDatesBetween() {
        App.printBonusDatesBetween(2010, 2015);
        assertEquals(
            "2010-01-02" + System.getProperty("line.separator") +
            "2011-11-02",
            this.outContent.toString().trim()
        );
    }
}
